.TH configure 1 "January 2025" "v1.0.1-dev.1" "administratrix GitOps"

.SH COMMAND

    \fBconfigure\fP [OPTIONS]

.SH SYNOPSIS

Configure a Git repository in the current working directory for GitOps

.SH DESCRIPTION

TODO

.SH OPTIONS

.B [--with-git]

.B [--with-gitops]

.B [--with-gitops-env]

.B [--with-framework[=FRAMEWORK]]

.B [--with-cicd[=CICDSERVICE]]

.B [--with-workflow=WORKFLOW]]

.B [--help]
print a long help message

.B [-h]
print a short help message

