.PHONY: gitops-doc gitops-build gitops-test gitops-release gitops-audit gitops-clean

gitops-doc:
	npm run doc
gitops-build:
	npm run build
gitops-test:
	npm test
gitops-release:
	@echo "'release' triggered, nothing to do"
gitops-audit:
	npm audit
gitops-clean:
	@echo "'clean' triggered, nothing to do"
