image: 'python:3.9-alpine'
definitions:
    caches:
        tox-test: '.tox/test/'
        tox-build: '.tox/build/'
        tox-build-docs: '.tox/build-docs/'
        tox-publish-docs: '.tox/publish-docs/'
        venv: '.venv/'
pipelines:
    branches:
        master:
            - step:
                name: '[GitOps] build'
                script:
                    - 'python3 -m pip install pipenv'
                    - 'mkdir -p .venv'
                    - 'python3 -m pipenv install -d'
            - step:
                name: '[GitOps] btest'
                script:
                    - 'python3 -m pip install pipenv'
                    - 'mkdir -p .venv'
                    - 'python3 -m pipenv install -d'
