.PHONY: gitops-doc gitops-build gitops-test gitops-release gitops-audit gitops-clean

gitops-doc:
	@echo "'doc' triggered, nothing to do"
gitops-build:
	@echo "'build' triggered, nothing to do"
gitops-test:
	@echo "'test' triggered, nothing to do"
gitops-release:
	@echo "'release' triggered, nothing to do"
gitops-audit:
	@echo "'audit' triggered, nothing to do"
gitops-clean:
	@echo "'clean' triggered, nothing to do"
